name: CI

on: [push]

jobs:
  builds:
    name: "Builds"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libglfw3-dev portaudio19-dev libgles2-mesa-dev python3 pkg-config ninja-build git
        git submodule init
        git submodule update
    - name: Compile release build
      run: ninja -f release.ninja
    - name: Compile debug build
      run: ninja -f debug.ninja

  tests:
    name: "Tests"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libcmocka-dev pkg-config ninja-build git
        git submodule init
        git submodule update
    - name: Compile tests
      run: ninja -f tests.ninja
    - name: Run 'nterrain-tests'
      run: ./nterrain-tests
