name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt install libglfw3-dev libgles2-mesa-dev python3 pkg-config ninja-build git
        git submodule init
        git submodule update
    - name: Compile release build
      run: ninja
    - name: Compile debug build
      run: ninja -f debug.ninja
