name: Ubuntu

on: [push]

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libglfw3-dev portaudio19-dev libmruby-dev libgles2-mesa-dev python3
        git submodule init
        git submodule update

    - name: Compile release build
      run: |
        mkdir build-release
        cd build-release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make

    - name: Compile debug build
      run: |
        mkdir build-debug
        cd build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make
